/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlaAutopista;
import Modelo.Bicicleta;
import Modelo.Camion;
import Modelo.Coche_Moto;
import Modelo.Vehiculo;
import Modelo.Gestora;
import Modelo.MyException;



public class Ventana extends javax.swing.JFrame {
    /**
     * el objeto que permite gestionar la información del número de vehiculos de
     * cada tipo que pasa por el peaje y del dinero recaudado
     */
    private final Gestora gestora=new Gestora();
    
    private Bicicleta bici;
    private Camion camion;
    private Coche_Moto auto;
    private Gestora gest;

    public Ventana() {
        initComponents();
        
        ControlaAutopista c = new ControlaAutopista(this, bici, camion, auto, gest);
        c.iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelEntrada = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldReferencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldKMS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldToneladas = new javax.swing.JTextField();
        jRadioButtonBici = new javax.swing.JRadioButton();
        jRadioButtonCamion = new javax.swing.JRadioButton();
        jRadioButtonCocheMoto = new javax.swing.JRadioButton();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jPanelConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PEAJE AUTOPISTA");

        jLabel4.setText("REFERENCIA");

        jLabel1.setText("KMS RECORRIDOS");

        jTextFieldKMS.setEnabled(false);

        jLabel2.setText("NUMERO DE TONELADAS");

        jTextFieldToneladas.setEnabled(false);

        buttonGroup1.add(jRadioButtonBici);
        jRadioButtonBici.setSelected(true);
        jRadioButtonBici.setText("Bicicleta");

        buttonGroup1.add(jRadioButtonCamion);
        jRadioButtonCamion.setText("Camion");
        jRadioButtonCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCamionActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCocheMoto);
        jRadioButtonCocheMoto.setText("Coche o moto");

        jButtonAceptar.setText("ACEPTAR");

        jButtonCancelar.setText("CANCELAR");

        javax.swing.GroupLayout jPanelEntradaLayout = new javax.swing.GroupLayout(jPanelEntrada);
        jPanelEntrada.setLayout(jPanelEntradaLayout);
        jPanelEntradaLayout.setHorizontalGroup(
            jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntradaLayout.createSequentialGroup()
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEntradaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldKMS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldToneladas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEntradaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jRadioButtonBici)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonCamion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonCocheMoto)
                        .addGap(18, 18, 18)))
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanelEntradaLayout.setVerticalGroup(
            jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEntradaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldReferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldKMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar))
                .addGap(24, 24, 24)
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldToneladas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBici)
                    .addComponent(jRadioButtonCamion)
                    .addComponent(jRadioButtonCocheMoto)
                    .addComponent(jButtonCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ENTRADA", jPanelEntrada);

        jPanelConsulta.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelConsultaComponentShown(evt);
            }
        });

        jTextArea1.setColumns(3);
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(10);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanelConsultaLayout = new javax.swing.GroupLayout(jPanelConsulta);
        jPanelConsulta.setLayout(jPanelConsultaLayout);
        jPanelConsultaLayout.setHorizontalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelConsultaLayout.setVerticalGroup(
            jPanelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelConsultaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTA", jPanelConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
  * Comprueba que los datos introducidos por el usuario son adecuados, y 
  * si no lo son define y lanza una excepción del tipo MyException con un mensaje
  * adecuado
  * La referencia del ticket de peaje introducida por el usuario debe ser una cadena compuesta por 6 dígitos
     * numéricos separados mediante un - de un grupo de 3 letras del espa?ol sin acentuar
     * seguido de 2 dígitos numéricos 
     * Por ejemplo: 
     * 432132-agX23 
     * 300212-Gz?45
     * 001234-Bje33
   * El número de kms recorridos debe ser un número comprendido entre 0.0 y 150.0
   * El número de toneladas de un camión debe ser un número comprendido entre 10.0 y 44.0 toneladas
  * @throws MyException 
  */
    private void comprobar() throws MyException{
       //modifica el método
    }
    /**
     * Con la información dada por el usuario define
     * un nuevo vehículo para actualizar la información
     */
   private void procesarEntrada() {
      Vehiculo nuevo=null;
        if (jRadioButtonBici.isSelected()){
            nuevo=new Bicicleta(jTextFieldReferencia.getText());
        }else if (jRadioButtonCamion.isSelected()){
            nuevo=new Camion(Float.parseFloat(jTextFieldKMS.getText()), Float.parseFloat(jTextFieldToneladas.getText()), jTextFieldReferencia.getText());
        }else if (jRadioButtonCocheMoto.isSelected()){
            nuevo=new Coche_Moto(Float.parseFloat(jTextFieldKMS.getText()), jTextFieldReferencia.getText());
        }
        gestora.actualizarInformacion(nuevo);
    }
   /**
    * deja el panel de entrada de la ventana como estaba cuando se inició la 
    * aplicación
    */
    private void cancelar(){
       //modifica el método
    }
    private void cancelarEntradaTexto() {
        jTextFieldReferencia.setText(null);
        jTextFieldKMS.setText(null);
        jTextFieldToneladas.setText(null);
    }   /**
    * programa lo que sea necesario hacer cuando el usuario selecciona el componente jRadioButtonCamion (Para calcular el peaje de un camión es necesarioconocer los kms recorridos y su tonelaje)
    */

/*
     Cuando el usuario elige ver el panel jPanelConsulta se debe visualizar 
  la información de la recaudación obtenida en el peaje con el siguiente formato:
            TOTAL RECAUDADO:	17,50 €

            VEHICULO MÁS FRECUENTE:BICICLETA - COCHES_MOTOS

            BICIS	MOTOS_COCHES	CAMIONES
            3       	3       	1       
            1,80    	14,30   	1,40  
     @param evt 
    */
    
    private void jPanelConsultaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelConsultaComponentShown
       //completa el método
    }//GEN-LAST:event_jPanelConsultaComponentShown

    private void jRadioButtonCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCamionActionPerformed
        //jTextFieldKMS.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonCamionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IllegalAccessException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton jButtonAceptar;
    public javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelConsulta;
    private javax.swing.JPanel jPanelEntrada;
    public javax.swing.JRadioButton jRadioButtonBici;
    public javax.swing.JRadioButton jRadioButtonCamion;
    public javax.swing.JRadioButton jRadioButtonCocheMoto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JTextField jTextFieldKMS;
    public javax.swing.JTextField jTextFieldReferencia;
    public javax.swing.JTextField jTextFieldToneladas;
    // End of variables declaration//GEN-END:variables
}
